namespace CPElite.Application.Abstractions;

public sealed record EaTournamentPlayerStatsAggregate(
    string EaPlayerId,
    string PlayerName,
    string? Position,
    int Matches,
    int Goals,
    int Assists,
    double? AverageRating,
    int PlayerOfTheMatch,
    int Shots,
    int PassesMade,
    int PassAttempts,
    double? PassSuccessRate,
    int TacklesMade,
    int TackleAttempts,
    double? TackleSuccessRate,
    int Saves,
    int GoalsConceded,
    int CleanSheetsAny,
    int CleanSheetsDef,
    int CleanSheetsGk,
    int RedCards,
    int SecondsPlayed,
    int? ArchetypeId,
    string? VproAttributes);
