-- TS Tournament localized UI content seed.
-- This file intentionally contains only fixed interface text:
-- labels, menus, titles, helper text, buttons and empty states.
-- It does NOT contain live/user/team/tournament/EA data.

insert into "LocalizedContents" ("Id", "Key", "Language", "Value", "Section", "Description", "UpdatedAt")
select gen_random_uuid(), data.key, data.language, data.value, data.section, data.description, now()
from (values
('brand.name','fr','TS Tournament','Global','Nom affiche de l application'),
('brand.subtitle','fr','Pro Clubs Tournament','Global','Sous-titre de marque'),
('nav.home','fr','Accueil','Navigation','Lien menu accueil'),
('nav.tournaments','fr','Tournois','Navigation','Lien menu tournois'),
('nav.mercato','fr','Mercato','Navigation','Lien menu mercato'),
('nav.my_team','fr','Mon equipe','Navigation','Lien menu equipe'),
('nav.my_account','fr','Mon compte','Navigation','Lien menu compte'),
('nav.admin','fr','Admin','Navigation','Lien menu admin'),
('nav.admin_content','fr','Textes','Navigation','Lien menu textes admin'),
('nav.login','fr','Se connecter','Navigation','Lien connexion'),
('nav.create_account','fr','Creer un compte','Navigation','Lien creation compte'),

('home.hero.eyebrow','fr','Prochain tournoi','Accueil','Eyebrow hero accueil'),
('home.hero.title','fr','TS Tournament organise ta soiree Pro Clubs.','Accueil','Titre hero accueil'),
('home.hero.subtitle','fr','Inscriptions, presence des 11 joueurs, tirage des poules, donnees EA et suivi Discord dans une seule experience.','Accueil','Sous-titre hero accueil'),
('home.hero.max_teams_label','fr','Equipes max','Accueil','Libelle meta tournoi max equipes'),
('home.hero.min_teams_label','fr','Minimum requis','Accueil','Libelle meta tournoi minimum equipes'),
('home.hero.entry_fee_label','fr','Prix equipe','Accueil','Libelle meta prix equipe'),
('home.hero.cta_tournament','fr','Voir le tournoi','Accueil','Bouton hero voir tournoi'),
('home.hero.cta_team','fr','Mon equipe','Accueil','Bouton hero equipe'),
('home.leaderboard.eyebrow','fr','Leaderboard','Accueil','Eyebrow leaderboard'),
('home.leaderboard.title','fr','Top 5 equipes','Accueil','Titre leaderboard'),
('home.search.eyebrow','fr','Recherche','Accueil','Eyebrow recherche'),
('home.search.title','fr','Trouver une equipe, un joueur ou une annonce','Accueil','Titre recherche'),
('home.search.placeholder','fr','Ex: BU ce soir, club recherche joueur, tournoi goodies...','Accueil','Placeholder recherche'),
('home.search.option_all','fr','Tout','Accueil','Filtre recherche tout'),
('home.search.option_teams','fr','Equipes','Accueil','Filtre recherche equipes'),
('home.search.option_players','fr','Joueurs','Accueil','Filtre recherche joueurs'),
('home.search.option_mercato','fr','Mercato','Accueil','Filtre recherche mercato'),
('home.search.option_tournaments','fr','Tournois','Accueil','Filtre recherche tournois'),
('home.search.button','fr','Rechercher','Accueil','Bouton recherche'),
('home.search.lock_title','fr','Connecte-toi pour rechercher.','Accueil','Titre recherche verrouillee'),
('home.search.lock_body','fr','Les annonces publiques restent visibles, mais la recherche et les fiches detaillees sont reservees aux comptes TS Tournament.','Accueil','Texte recherche verrouillee'),

('account.page.eyebrow','fr','Compte joueur','Compte','Eyebrow compte'),
('account.page.title_authenticated','fr','Mon profil joueur','Compte','Titre compte connecte'),
('account.page.title_anonymous','fr','Creation de compte joueur','Compte','Titre compte non connecte'),
('account.page.subtitle_authenticated','fr','Profil EA, club actif et performances en tournoi agreges depuis les matchs stockes.','Compte','Sous-titre compte connecte'),
('account.page.subtitle_anonymous','fr','Cherche ton club EA, selectionne ton joueur, puis cree ton acces TS Tournament.','Compte','Sous-titre compte non connecte'),
('account.avatar.label','fr','Photo de profil','Compte','Label photo profil'),
('account.avatar.help','fr','Visible sur ton profil, ton club et les classements joueur.','Compte','Aide upload photo'),
('account.avatar.saving','fr','Sauvegarde en cours...','Compte','Etat upload photo'),
('account.identity.eyebrow','fr','Identite joueur','Compte','Eyebrow identite'),
('account.identity.display_name','fr','Nom joueur','Compte','Label nom joueur'),
('account.identity.gamertag','fr','Gamertag','Compte','Label gamertag'),
('account.identity.ea_id','fr','EA Sports ID','Compte','Label EA ID'),
('account.identity.discord','fr','Discord','Compte','Label Discord'),
('account.identity.platform','fr','Plateforme','Compte','Label plateforme'),
('account.identity.timezone','fr','Fuseau horaire','Compte','Label fuseau horaire'),
('account.identity.active_club','fr','Club actif','Compte','Label club actif'),
('account.identity.role','fr','Role','Compte','Label role'),
('account.registration.step1','fr','Etape 1','Compte','Etape inscription club'),
('account.registration.find_club_title','fr','Trouve ton club EA','Compte','Titre recherche club inscription'),
('account.registration.find_club_body','fr','Le joueur cherche son club EA, voit si le club est deja dans TS Tournament, puis selectionne le profil EA qui lui correspond.','Compte','Texte recherche club inscription'),
('account.registration.club_name','fr','Nom du club','Compte','Label nom club'),
('account.registration.search_club','fr','Chercher club','Compte','Bouton chercher club'),
('account.registration.step2','fr','Etape 2','Compte','Etape creation compte'),
('account.registration.quick_create','fr','Creation rapide','Compte','Titre creation rapide'),
('account.registration.create_account','fr','Creer le compte','Compte','Bouton creation compte'),
('account.session.active','fr','Session active','Compte','Titre session active'),
('account.session.logout','fr','Deconnexion','Compte','Bouton deconnexion'),

('teams.hero.eyebrow','fr','Club house','Club','Eyebrow page club'),
('teams.hero.title','fr','Lie ton club, verrouille l EA ID, construis ton effectif.','Club','Titre page club'),
('teams.hero.subtitle','fr','Le owner recherche son club par nom, TS Tournament recupere les donnees utiles, les stocke chez nous et les garde a jour avec la synchro periodique.','Club','Sous-titre page club'),
('teams.next.eyebrow','fr','Prochaine evolution','Club','Eyebrow prochaine evolution'),
('teams.next.title','fr','EA ID joueur','Club','Titre prochaine evolution'),
('teams.next.body','fr','Meme logique cote joueur : premiere liaison depuis l EA Sports ID, stockage local, puis mise a jour par le cron.','Club','Texte prochaine evolution'),
('teams.identity.eyebrow','fr','Identite club','Club','Eyebrow identite club'),
('teams.images.eyebrow','fr','Logo & banniere','Club','Eyebrow images club'),
('teams.images.title','fr','Image du club','Club','Titre images club'),
('teams.images.logo','fr','Logo equipe','Club','Label logo equipe'),
('teams.images.banner','fr','Banniere equipe','Club','Label banniere equipe'),
('teams.images.logo_empty','fr','PNG, JPG ou WebP','Club','Aide logo vide'),
('teams.images.banner_empty','fr','Image large recommandee','Club','Aide banniere vide'),
('teams.create.eyebrow','fr','Creation equipe','Club','Eyebrow creation equipe'),
('teams.create.search_title','fr','Rechercher le club EA','Club','Titre recherche club EA'),
('teams.create.search_button','fr','Rechercher','Club','Bouton rechercher club'),
('teams.create.help','fr','Tape le nom du club pour recuperer les donnees disponibles et selectionner le bon EA club ID.','Club','Aide recherche club'),
('teams.create.submit','fr','Creer equipe et stocker les donnees','Club','Bouton creation equipe'),
('teams.selector.my_clubs','fr','Mes clubs','Club','Eyebrow clubs owner'),
('teams.selector.my_club','fr','Mon club','Club','Eyebrow club joueur'),
('teams.selector.owner_selection','fr','Selection club owner','Club','Titre selection owner'),
('teams.selector.active_club','fr','Club actif','Club','Titre club actif'),
('teams.selector.refresh','fr','Rafraichir','Club','Bouton rafraichir'),
('teams.data.eyebrow','fr','Donnees stockees','Club','Eyebrow donnees stockees'),
('teams.data.ea_stats','fr','Stats generales EA','Club','Titre stats EA'),
('teams.data.app_stats','fr','Stats TS Tournament','Club','Titre stats app'),
('teams.roster.title','fr','Effectif actif complet','Club','Titre effectif actif'),
('teams.friendlies.eyebrow','fr','Matchs amicaux EA','Club','Eyebrow amicaux EA'),
('teams.friendlies.title','fr','5 derniers matchs','Club','Titre amicaux EA'),
('teams.friendlies.select','fr','Match a consulter','Club','Label choix match'),
('teams.friendlies.empty_title','fr','Aucun amical EA stocke','Club','Titre aucun amical'),
('teams.friendlies.empty_body','fr','Rafraichis les donnees EA du club pour recuperer les derniers matchs amicaux et leurs details joueurs.','Club','Texte aucun amical'),

('mercato.page.eyebrow','fr','Mercato','Mercato','Eyebrow mercato'),
('mercato.page.title','fr','Annonces joueurs','Mercato','Titre mercato'),
('mercato.search.placeholder','fr','Poste, disponibilite, club, plateforme...','Mercato','Placeholder recherche mercato'),
('mercato.search.button','fr','Rechercher','Mercato','Bouton recherche mercato'),

('tournaments.page.eyebrow','fr','Espace joueur','Tournois','Eyebrow page tournois'),
('tournaments.page.title','fr','Tournois disponibles','Tournois','Titre page tournois'),
('tournaments.page.subtitle_authenticated','fr','Le owner peut gerer plusieurs clubs, inscrire le bon club au bon tournoi, puis soumettre les 11 joueurs qui doivent confirmer leur presence.','Tournois','Sous-titre tournois connecte'),
('tournaments.page.subtitle_anonymous','fr','Consulte les prochains tournois disponibles. Cree ton compte pour inscrire ton equipe et acceder au suivi complet.','Tournois','Sous-titre tournois public'),
('tournaments.card.simple','fr','Tournoi simple','Tournois','Type tournoi simple'),
('tournaments.card.goodies','fr','Tournoi goodies','Tournois','Type tournoi goodies'),
('tournaments.card.body','fr','Tournoi ouvert aux equipes Pro Clubs. Il reste des places: cree ton compte et ramene ton equipe pour participer.','Tournois','Texte carte tournoi'),
('tournaments.card.goodies_label','fr','Goodies','Tournois','Label goodies'),
('tournaments.card.cta_authenticated','fr','Preparer mon equipe','Tournois','CTA tournoi connecte'),
('tournaments.card.cta_anonymous','fr','Creer ton compte et ramener ton equipe','Tournois','CTA tournoi public'),
('tournaments.public.eyebrow','fr','Acces public','Tournois','Eyebrow acces public'),
('tournaments.public.title','fr','Des places sont encore disponibles','Tournois','Titre acces public'),
('tournaments.public.body','fr','Pour inscrire une equipe, voir tes tournois, gerer ton roster ou valider les presences, il faut creer un compte TS Tournament.','Tournois','Texte acces public'),
('tournaments.tabs.live','fr','En cours','Tournois','Onglet en cours'),
('tournaments.tabs.upcoming','fr','A venir','Tournois','Onglet a venir'),
('tournaments.tabs.past','fr','Passes','Tournois','Onglet passes'),
('tournaments.owner.eyebrow','fr','Owner desk','Tournois','Eyebrow owner desk'),
('tournaments.owner.title','fr','Soumettre les 11 joueurs','Tournois','Titre soumettre roster'),
('tournaments.owner.body','fr','Un owner peut gerer plusieurs clubs. Il choisit le club inscrit ce soir, selectionne 11 joueurs, puis chaque joueur recoit sa confirmation de presence.','Tournois','Texte soumettre roster'),
('tournaments.owner.submit','fr','Soumettre les 11','Tournois','Bouton soumettre roster'),
('tournaments.owner.remind','fr','Relancer les joueurs','Tournois','Bouton relance joueurs'),

('admin.content.page.eyebrow','fr','Admin contenu','Admin textes','Eyebrow admin contenu'),
('admin.content.page.title','fr','Textes traduisibles','Admin textes','Titre admin contenu'),
('admin.content.page.subtitle','fr','Chaque libelle important doit devenir une cle modifiable ici, avec une version francaise et anglaise.','Admin textes','Sous-titre admin contenu'),
('admin.content.catalog.eyebrow','fr','Catalogue','Admin textes','Eyebrow catalogue textes'),
('admin.content.catalog.empty_title','fr','Aucun texte pour cette langue','Admin textes','Titre catalogue vide'),
('admin.content.catalog.empty_body','fr','Ajoute une premiere cle. Exemple: nav.home, home.hero.title, tournaments.join.cta.','Admin textes','Texte catalogue vide'),
('admin.content.editor.eyebrow','fr','Edition','Admin textes','Eyebrow edition texte'),
('admin.content.editor.new_title','fr','Nouveau texte','Admin textes','Titre nouveau texte'),
('admin.content.editor.edit_title','fr','Modifier texte','Admin textes','Titre modifier texte'),
('admin.content.form.key','fr','Cle','Admin textes','Label cle'),
('admin.content.form.language','fr','Langue','Admin textes','Label langue'),
('admin.content.form.section','fr','Section','Admin textes','Label section'),
('admin.content.form.description','fr','Description','Admin textes','Label description'),
('admin.content.form.value','fr','Texte','Admin textes','Label valeur texte'),
('admin.content.form.save','fr','Sauvegarder','Admin textes','Bouton sauvegarder texte'),
('admin.content.form.new','fr','Nouveau','Admin textes','Bouton nouveau texte'),

('brand.name','en','TS Tournament','Global','Displayed app name'),
('brand.subtitle','en','Pro Clubs Tournament','Global','Brand subtitle'),
('nav.home','en','Home','Navigation','Home menu link'),
('nav.tournaments','en','Tournaments','Navigation','Tournaments menu link'),
('nav.mercato','en','Transfer market','Navigation','Mercato menu link'),
('nav.my_team','en','My team','Navigation','Team menu link'),
('nav.my_account','en','My account','Navigation','Account menu link'),
('nav.admin','en','Admin','Navigation','Admin menu link'),
('nav.admin_content','en','Texts','Navigation','Admin texts menu link'),
('nav.login','en','Log in','Navigation','Login link'),
('nav.create_account','en','Create account','Navigation','Create account link'),

('home.hero.eyebrow','en','Next tournament','Home','Home hero eyebrow'),
('home.hero.title','en','TS Tournament organizes your Pro Clubs night.','Home','Home hero title'),
('home.hero.subtitle','en','Registrations, 11-player availability, group draw, EA data and Discord follow-up in one experience.','Home','Home hero subtitle'),
('home.hero.max_teams_label','en','Max teams','Home','Max teams meta label'),
('home.hero.min_teams_label','en','Minimum required','Home','Minimum teams meta label'),
('home.hero.entry_fee_label','en','Team fee','Home','Team fee meta label'),
('home.hero.cta_tournament','en','View tournament','Home','Hero tournament CTA'),
('home.hero.cta_team','en','My team','Home','Hero team CTA'),
('home.leaderboard.eyebrow','en','Leaderboard','Home','Leaderboard eyebrow'),
('home.leaderboard.title','en','Top 5 teams','Home','Leaderboard title'),
('home.search.eyebrow','en','Search','Home','Search eyebrow'),
('home.search.title','en','Find a team, player or post','Home','Search title'),
('home.search.placeholder','en','Ex: ST tonight, club needs player, goodies tournament...','Home','Search placeholder'),
('home.search.option_all','en','All','Home','All search filter'),
('home.search.option_teams','en','Teams','Home','Teams search filter'),
('home.search.option_players','en','Players','Home','Players search filter'),
('home.search.option_mercato','en','Transfer market','Home','Mercato search filter'),
('home.search.option_tournaments','en','Tournaments','Home','Tournaments search filter'),
('home.search.button','en','Search','Home','Search button'),
('home.search.lock_title','en','Log in to search.','Home','Locked search title'),
('home.search.lock_body','en','Public posts remain visible, but search and detailed profiles are reserved for TS Tournament accounts.','Home','Locked search body'),

('account.page.eyebrow','en','Player account','Account','Account eyebrow'),
('account.page.title_authenticated','en','My player profile','Account','Authenticated account title'),
('account.page.title_anonymous','en','Create player account','Account','Anonymous account title'),
('account.page.subtitle_authenticated','en','EA profile, active club and tournament performances aggregated from stored matches.','Account','Authenticated account subtitle'),
('account.page.subtitle_anonymous','en','Find your EA club, select your player, then create your TS Tournament access.','Account','Anonymous account subtitle'),
('account.avatar.label','en','Profile photo','Account','Profile photo label'),
('account.avatar.help','en','Visible on your profile, club and player rankings.','Account','Profile photo help'),
('account.avatar.saving','en','Saving...','Account','Profile photo saving state'),
('account.identity.eyebrow','en','Player identity','Account','Identity eyebrow'),
('account.identity.display_name','en','Player name','Account','Display name label'),
('account.identity.gamertag','en','Gamertag','Account','Gamertag label'),
('account.identity.ea_id','en','EA Sports ID','Account','EA ID label'),
('account.identity.discord','en','Discord','Account','Discord label'),
('account.identity.platform','en','Platform','Account','Platform label'),
('account.identity.timezone','en','Time zone','Account','Time zone label'),
('account.identity.active_club','en','Active club','Account','Active club label'),
('account.identity.role','en','Role','Account','Role label'),

('teams.hero.eyebrow','en','Club house','Club','Club page eyebrow'),
('teams.hero.title','en','Link your club, lock the EA ID, build your roster.','Club','Club page title'),
('teams.hero.subtitle','en','The owner searches the club by name, TS Tournament retrieves useful data, stores it locally and keeps it updated through scheduled sync.','Club','Club page subtitle'),
('teams.create.search_title','en','Search EA club','Club','EA club search title'),
('teams.create.search_button','en','Search','Club','EA club search button'),
('teams.create.submit','en','Create team and store data','Club','Create team button'),
('teams.selector.my_clubs','en','My clubs','Club','Owner clubs eyebrow'),
('teams.selector.my_club','en','My club','Club','Player club eyebrow'),
('teams.selector.refresh','en','Refresh','Club','Refresh button'),
('teams.data.ea_stats','en','General EA stats','Club','EA stats title'),
('teams.data.app_stats','en','TS Tournament stats','Club','App stats title'),
('teams.roster.title','en','Full active roster','Club','Active roster title'),
('teams.friendlies.title','en','Last 5 matches','Club','Friendlies title'),

('mercato.page.eyebrow','en','Transfer market','Mercato','Mercato eyebrow'),
('mercato.page.title','en','Player posts','Mercato','Mercato title'),
('mercato.search.button','en','Search','Mercato','Mercato search button'),

('tournaments.page.eyebrow','en','Player area','Tournaments','Tournaments page eyebrow'),
('tournaments.page.title','en','Available tournaments','Tournaments','Tournaments page title'),
('tournaments.card.simple','en','Standard tournament','Tournaments','Standard tournament type'),
('tournaments.card.goodies','en','Goodies tournament','Tournaments','Goodies tournament type'),
('tournaments.card.body','en','Tournament open to Pro Clubs teams. Spots are still available: create your account and bring your team to participate.','Tournaments','Tournament card body'),
('tournaments.card.cta_authenticated','en','Prepare my team','Tournaments','Authenticated tournament CTA'),
('tournaments.card.cta_anonymous','en','Create your account and bring your team','Tournaments','Anonymous tournament CTA'),
('tournaments.tabs.live','en','Live','Tournaments','Live tab'),
('tournaments.tabs.upcoming','en','Upcoming','Tournaments','Upcoming tab'),
('tournaments.tabs.past','en','Past','Tournaments','Past tab'),
('tournaments.owner.title','en','Submit the 11 players','Tournaments','Roster submission title'),
('tournaments.owner.submit','en','Submit the 11','Tournaments','Submit roster button'),
('tournaments.owner.remind','en','Remind players','Tournaments','Remind players button'),

('admin.content.page.eyebrow','en','Content admin','Admin texts','Content admin eyebrow'),
('admin.content.page.title','en','Translatable texts','Admin texts','Content admin title'),
('admin.content.page.subtitle','en','Every important label must become an editable key here, with a French and English version.','Admin texts','Content admin subtitle'),
('admin.content.catalog.eyebrow','en','Catalog','Admin texts','Text catalog eyebrow'),
('admin.content.catalog.empty_title','en','No text for this language','Admin texts','Empty catalog title'),
('admin.content.editor.eyebrow','en','Editing','Admin texts','Text editor eyebrow'),
('admin.content.editor.new_title','en','New text','Admin texts','New text title'),
('admin.content.editor.edit_title','en','Edit text','Admin texts','Edit text title'),
('admin.content.form.key','en','Key','Admin texts','Key label'),
('admin.content.form.language','en','Language','Admin texts','Language label'),
('admin.content.form.section','en','Section','Admin texts','Section label'),
('admin.content.form.description','en','Description','Admin texts','Description label'),
('admin.content.form.value','en','Text','Admin texts','Text value label'),
('admin.content.form.save','en','Save','Admin texts','Save text button'),
('admin.content.form.new','en','New','Admin texts','New text button')
) as data(key, language, value, section, description)
on conflict ("Key", "Language") do update set
  "Value" = excluded."Value",
  "Section" = excluded."Section",
  "Description" = excluded."Description",
  "UpdatedAt" = excluded."UpdatedAt";
