// <auto-generated />
using System;
using CPElite.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CPElite.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CPEliteDbContext))]
    [Migration("20260724120216_AddTeamRankings")]
    partial class AddTeamRankings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CPElite.Domain.Entities.ChampionTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CrownedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("DethronedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NextEntryDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "IsActive");

                    b.ToTable("ChampionTitles");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaApiCacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.ToTable("EaApiCacheEntries");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaClubSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Division")
                        .HasColumnType("integer");

                    b.Property<long>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MembersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("EaClubSnapshots");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaDiagnosticProbe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClubName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("RawLength")
                        .HasColumnType("integer");

                    b.Property<string>("RawPreview")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("EaDiagnosticProbes");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaFriendlyMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwayClubName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("AwayEaClubId")
                        .HasColumnType("bigint");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<long>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<string>("EaMatchId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("HomeClubName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("HomeEaClubId")
                        .HasColumnType("bigint");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TournamentMatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentMatchId");

                    b.HasIndex("TeamId", "EaMatchId")
                        .IsUnique();

                    b.HasIndex("TeamId", "PlayedAt");

                    b.ToTable("EaFriendlyMatches");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMatchClubStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Assists")
                        .HasColumnType("integer");

                    b.Property<string>("CrestAssetId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EaFriendlyMatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EaTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer");

                    b.Property<int?>("GoalsConceded")
                        .HasColumnType("integer");

                    b.Property<string>("KitColor1")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("KitColor2")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("KitColor3")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("KitColor4")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("Losses")
                        .HasColumnType("integer");

                    b.Property<int?>("PassAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("PassesMade")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerOfTheMatch")
                        .HasColumnType("integer");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("Saves")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<int?>("Shots")
                        .HasColumnType("integer");

                    b.Property<string>("StadiumName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("TackleAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("TacklesMade")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Ties")
                        .HasColumnType("integer");

                    b.Property<bool?>("WinnerByDnf")
                        .HasColumnType("boolean");

                    b.Property<int?>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EaFriendlyMatchId", "EaClubId")
                        .IsUnique();

                    b.ToTable("EaMatchClubStats");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMatchPlayerStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArchetypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Assists")
                        .HasColumnType("integer");

                    b.Property<int?>("BallDiveSaves")
                        .HasColumnType("integer");

                    b.Property<int?>("CleanSheetsAny")
                        .HasColumnType("integer");

                    b.Property<int?>("CleanSheetsDef")
                        .HasColumnType("integer");

                    b.Property<int?>("CleanSheetsGk")
                        .HasColumnType("integer");

                    b.Property<int?>("CrossSaves")
                        .HasColumnType("integer");

                    b.Property<long>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EaFriendlyMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("EaPlayerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("GameTime")
                        .HasColumnType("integer");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer");

                    b.Property<int?>("GoalsConceded")
                        .HasColumnType("integer");

                    b.Property<int?>("GoodDirectionSaves")
                        .HasColumnType("integer");

                    b.Property<string>("MatchEventAggregate0")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MatchEventAggregate1")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MatchEventAggregate2")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MatchEventAggregate3")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ParrySaves")
                        .HasColumnType("integer");

                    b.Property<int?>("PassAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("PassesMade")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("PlayerOfTheMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("PunchSaves")
                        .HasColumnType("integer");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RealtimeGame")
                        .HasColumnType("integer");

                    b.Property<int?>("RealtimeIdle")
                        .HasColumnType("integer");

                    b.Property<int?>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int?>("ReflexSaves")
                        .HasColumnType("integer");

                    b.Property<int?>("Saves")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondsPlayed")
                        .HasColumnType("integer");

                    b.Property<int?>("Shots")
                        .HasColumnType("integer");

                    b.Property<int?>("TackleAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("TacklesMade")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("VproAttributes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "PlayerName");

                    b.HasIndex("EaFriendlyMatchId", "EaPlayerId", "EaClubId")
                        .IsUnique();

                    b.ToTable("EaMatchPlayerStats");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMatchSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "MatchType")
                        .IsUnique();

                    b.ToTable("EaMatchSnapshots");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMemberStatsSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("EaMemberStatsSnapshots");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaPlayerProfileSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AllClubsAssists")
                        .HasColumnType("integer");

                    b.Property<double?>("AllClubsAverageRating")
                        .HasColumnType("double precision");

                    b.Property<int?>("AllClubsGoals")
                        .HasColumnType("integer");

                    b.Property<int?>("AllClubsMatches")
                        .HasColumnType("integer");

                    b.Property<int?>("AllClubsPlayerOfTheMatch")
                        .HasColumnType("integer");

                    b.Property<int?>("Assists")
                        .HasColumnType("integer");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int?>("CleanSheets")
                        .HasColumnType("integer");

                    b.Property<int?>("CleanSheetsGk")
                        .HasColumnType("integer");

                    b.Property<long>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<string>("EaPlayerId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("Matches")
                        .HasColumnType("integer");

                    b.Property<int?>("Overall")
                        .HasColumnType("integer");

                    b.Property<int?>("PassAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("PassesMade")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("PlayerOfTheMatch")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("PrevGoals")
                        .HasColumnType("integer");

                    b.Property<string>("ProName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int?>("Saves")
                        .HasColumnType("integer");

                    b.Property<int?>("ShotSuccessRate")
                        .HasColumnType("integer");

                    b.Property<int?>("Shots")
                        .HasColumnType("integer");

                    b.Property<int?>("StoredAllClubsGoalContributions")
                        .HasColumnType("integer");

                    b.Property<double?>("StoredAllClubsGoalContributionsPerMatch")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredAllClubsPlayerOfTheMatchRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredAssistsPerMatch")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredCleanSheetsDefRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredCleanSheetsGkRate")
                        .HasColumnType("double precision");

                    b.Property<int?>("StoredGoalContributions")
                        .HasColumnType("integer");

                    b.Property<double?>("StoredGoalContributionsPerMatch")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredGoalsPerMatch")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredPassSuccessRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredPassesMadePerMatch")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredPlayerOfTheMatchRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredTackleSuccessRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("StoredTacklesMadePerMatch")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TackleAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("TacklesMade")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.Property<int?>("WinRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerName");

                    b.HasIndex("TeamId", "EaPlayerId")
                        .IsUnique();

                    b.ToTable("EaPlayerProfileSnapshots");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.LocalizedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Section")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Language")
                        .IsUnique();

                    b.HasIndex("Language", "Section");

                    b.ToTable("LocalizedContents");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.MatchScoreSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProofUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchScoreSubmissions");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiscordUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long?>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset?>("InviteCodeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("RequireJoinApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TikTokUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TwitchUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId", "Status");

                    b.ToTable("TeamJoinRequests");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamManagerClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalThreshold")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClaimantUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedRole")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClaimantUserId");

                    b.HasIndex("TeamId", "ClaimantUserId", "Status");

                    b.ToTable("TeamManagerClaims");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamManagerClaimVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoterUserId");

                    b.HasIndex("ClaimId", "VoterUserId")
                        .IsUnique();

                    b.HasIndex("TeamId", "VoterUserId");

                    b.ToTable("TeamManagerClaimVotes");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamPlayerDemand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NeededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TeamId", "Status");

                    b.HasIndex("Status", "NeededAt", "ExpiresAt");

                    b.ToTable("TeamPlayerDemands");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique();

                    b.ToTable("TeamPositions");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CleanSheets")
                        .HasColumnType("integer");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int>("Finals")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastTournamentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Podiums")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Titles")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentsPlayed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Points");

                    b.HasIndex("Rank");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamRankings");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamScheduleSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "DayOfWeek", "StartTime");

                    b.ToTable("TeamScheduleSlots");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamSlotAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamSlotPackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamSlotPackageId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId", "ReleasedAt");

                    b.ToTable("TeamSlotAssignments");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamSlotPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("numeric");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("PurchasedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PurchasedByUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamSlotPackages");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoPublishPerfectScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("EaMonitoringEndsMinutesAfter")
                        .HasColumnType("integer");

                    b.Property<int>("EaMonitoringStartsMinutesBefore")
                        .HasColumnType("integer");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EstimatedPrizeBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("GoodiesDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCashPrize")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<int>("MinTeams")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PlayerRestrictionsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("RegistrationEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RegistrationLockAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RegistrationStartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScoreRecoveryIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<int>("ScoreRecoveryMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EaLookupFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EaLookupUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EaRawMatchJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("GroupName")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "RoundNumber");

                    b.HasIndex("TournamentId", "Stage", "GroupName");

                    b.ToTable("TournamentMatches");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentMoment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsPublishedToDiscord")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedToDiscordAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsPublishedToDiscord", "CreatedAt");

                    b.HasIndex("TournamentId", "MatchId");

                    b.ToTable("TournamentMoments");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentPlayerConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DelayMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLoan")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LoanApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LoanApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoanFromTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("ReplacementSuggested")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresOwnerNotification")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("IsLoan", "LoanFromTeamId");

                    b.HasIndex("TournamentId", "TeamId", "Status");

                    b.HasIndex("TournamentId", "TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("TournamentPlayerConfirmations");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordChannelId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DiscordGuildId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DiscordMessageId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DiscordRequestedByUserId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsPaymentComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId", "TeamId")
                        .IsUnique();

                    b.ToTable("TournamentRegistrations");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentScoreAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer");

                    b.Property<bool>("DuplicateCandidateDetected")
                        .HasColumnType("boolean");

                    b.Property<bool>("DurationLooksComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("EaMatchId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("ManualAwayScore")
                        .HasColumnType("integer");

                    b.Property<int?>("ManualHomeScore")
                        .HasColumnType("integer");

                    b.Property<bool>("PlayersMatched")
                        .HasColumnType("boolean");

                    b.Property<string>("RawCandidateJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("ScoreMatched")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("TeamsMatched")
                        .HasColumnType("boolean");

                    b.Property<bool>("TimestampMatched")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentMatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TournamentId", "AttemptedAt");

                    b.HasIndex("TournamentMatchId", "AttemptedAt");

                    b.ToTable("TournamentScoreAudits");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long?>("EaClubId")
                        .HasColumnType("bigint");

                    b.Property<string>("EaClubName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("EaIdentityVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("EaIdentityVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EaSportsId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Gamertag")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.UserTournamentAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTournamentAccesses");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.ChampionTitle", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaClubSnapshot", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaFriendlyMatch", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMatchClubStat", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.EaFriendlyMatch", "Match")
                        .WithMany("ClubStats")
                        .HasForeignKey("EaFriendlyMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMatchPlayerStat", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.EaFriendlyMatch", "Match")
                        .WithMany("PlayerStats")
                        .HasForeignKey("EaFriendlyMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMatchSnapshot", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaMemberStatsSnapshot", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaPlayerProfileSnapshot", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.MatchScoreSubmission", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.TournamentMatch", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany("JoinRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamManagerClaim", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.User", "ClaimantUser")
                        .WithMany()
                        .HasForeignKey("ClaimantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaimantUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamManagerClaimVote", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.TeamManagerClaim", "Claim")
                        .WithMany("Votes")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.User", "VoterUser")
                        .WithMany()
                        .HasForeignKey("VoterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("VoterUser");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamPlayerDemand", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany("PlayerDemands")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamPosition", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany("Positions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamRanking", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamScheduleSlot", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany("ScheduleSlots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamSlotAssignment", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.TeamSlotPackage", "Package")
                        .WithMany()
                        .HasForeignKey("TeamSlotPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamSlotPackage", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.User", "PurchasedByUser")
                        .WithMany()
                        .HasForeignKey("PurchasedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchasedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentMatch", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentPlayerConfirmation", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentRegistration", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TournamentScoreAudit", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPElite.Domain.Entities.TournamentMatch", "TournamentMatch")
                        .WithMany()
                        .HasForeignKey("TournamentMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("TournamentMatch");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.UserTournamentAccess", b =>
                {
                    b.HasOne("CPElite.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.EaFriendlyMatch", b =>
                {
                    b.Navigation("ClubStats");

                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.Team", b =>
                {
                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("PlayerDemands");

                    b.Navigation("Positions");

                    b.Navigation("ScheduleSlots");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.TeamManagerClaim", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CPElite.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
